"""
Write desktop/src-tauri/tests/fixtures/claim_p3.json: tokens and a policy
signed by app.core.claim_signing with THROWAWAY keys, so cargo test proves a
token made by the Python signer verifies in Rust (PLAN-32E P3, task #6172).
The private seeds are discarded; only public keys land in the file.

    cd backend && venv/bin/python scripts/make_claim_p3_fixture.py
"""
import base64
import hashlib
import json
import os
import pathlib
import sys

sys.path.insert(0, str(pathlib.Path(__file__).resolve().parents[1]))

from cryptography.hazmat.primitives import serialization  # noqa: E402
from cryptography.hazmat.primitives.asymmetric.ed25519 import Ed25519PrivateKey  # noqa: E402

from app.core import claim_signing  # noqa: E402

NOW = 1_800_000_000
URL = "https://www.youtube.com/watch?v=dQw4w9WgXcQ"
DEVICE = hashlib.sha256(b"fixture-machine").hexdigest()
OUT = pathlib.Path(__file__).resolve().parents[2] / "desktop/src-tauri/tests/fixtures/claim_p3.json"


def use_new_key(kid: str) -> str:
    k = Ed25519PrivateKey.generate()
    seed = k.private_bytes(serialization.Encoding.Raw, serialization.PrivateFormat.Raw, serialization.NoEncryption())
    os.environ["CLIENT_QUOTA_SIGNING_KEY"] = base64.b64encode(seed).decode()
    os.environ["CLIENT_QUOTA_SIGNING_KID"] = kid
    return claim_signing.public_key_b64()


def main() -> None:
    pub1 = use_new_key("t1")
    token = claim_signing.claim_token("0123456789abcdef01234567", [URL], DEVICE, now=NOW)
    policy = claim_signing.policy(True, 3, "0.6.0", now=NOW)
    policy_off = claim_signing.policy(False, 3, "0.6.0", now=NOW)
    pub2 = use_new_key("t2")  # the "next" key of a rotation
    token_next = claim_signing.claim_token("fedcba9876543210fedcba98", [URL], DEVICE, now=NOW)
    use_new_key("t1")         # same kid, key NOT embedded: must be refused
    token_foreign = claim_signing.claim_token("0123456789abcdef01234567", [URL], DEVICE, now=NOW)
    OUT.parent.mkdir(parents=True, exist_ok=True)
    OUT.write_text(json.dumps({
        "_note": "Generated by backend/scripts/make_claim_p3_fixture.py with throwaway keys (seeds discarded).",
        "keys": {"t1": pub1, "t2": pub2},
        "now": NOW, "url": URL, "device": DEVICE, "cid": "0123456789abcdef01234567", "grace": 3,
        "token": token, "token_next_key": token_next, "token_foreign_key": token_foreign,
        "policy": policy, "policy_off": policy_off,
    }, indent=2) + "\n", encoding="utf-8")
    print(f"wrote {OUT}")


if __name__ == "__main__":
    main()
