import { useEffect, useState } from 'react'
import { cn } from '../../utils/cn'
import type { AddCookieFormData, ImportMode } from './cookie.types'
import { DEFAULT_ADD_FORM } from './cookie.types'
import { testCookieApi, type TestCookieResponse } from '../../api/cookies'

// ─── Constants ─────────────────────────────────────────────────────────────────

const PLATFORMS = [
  'youtube', 'instagram', 'tiktok', 'twitter', 'facebook',
  'bilibili', 'douyin', 'soundcloud', 'pinterest', 'reddit', 'vimeo', 'threads',
]

const IMPORT_MODES: Array<{ value: ImportMode; label: string }> = [
  { value: 'netscape', label: 'Netscape' },
  { value: 'json',     label: 'JSON'     },
  { value: 'raw',      label: 'Raw'      },
]

const FORMAT_HINTS: Record<ImportMode, { placeholder: string; hint: string }> = {
  netscape: {
    placeholder:
      '# Netscape HTTP Cookie File\n# Generated by EditThisCookie\n.youtube.com\tTRUE\t/\tFALSE\t1735689600\tSID\tABC123xyz...\n.youtube.com\tTRUE\t/\tTRUE\t1735689600\tHSID\tDEF456uvw...',
    hint: 'Export from browser extension (EditThisCookie, Cookie Editor) using Netscape format.',
  },
  json: {
    placeholder:
      '[\n  {\n    "name": "SID",\n    "value": "ABC123xyz...",\n    "domain": ".youtube.com",\n    "path": "/",\n    "secure": false,\n    "httpOnly": false,\n    "expirationDate": 1735689600\n  }\n]',
    hint: 'Export from browser DevTools → Application → Cookies → right-click → copy as JSON.',
  },
  raw: {
    placeholder:
      'SID=ABC123xyz...; HSID=DEF456uvw...; SSID=GHI789rst...; APISID=JKL012mno...',
    hint: 'Paste the raw Cookie header value (semicolon-separated name=value pairs).',
  },
}

// ─── Sub-components ────────────────────────────────────────────────────────────

function Label({ children, required }: { children: string; required?: boolean }) {
  return (
    <label className="mb-1.5 block text-xs font-medium text-fg-muted">
      {children}
      {required && <span className="ml-0.5 text-danger">*</span>}
    </label>
  )
}

function InputBase({ className, ...props }: React.InputHTMLAttributes<HTMLInputElement>) {
  return (
    <input
      className={cn(
        'w-full rounded-lg border border-line bg-surface px-3 py-2 text-xs text-fg',
        'placeholder:text-fg-muted outline-none transition-colors',
        'focus:border-line focus:ring-1 focus:ring-line-strong',
        className,
      )}
      {...props}
    />
  )
}

function SelectBase({ className, ...props }: React.SelectHTMLAttributes<HTMLSelectElement>) {
  return (
    <select
      className={cn(
        'w-full rounded-lg border border-line bg-surface px-3 py-2 text-xs text-fg',
        'outline-none transition-colors focus:border-line',
        className,
      )}
      {...props}
    />
  )
}

// ─── Main modal ────────────────────────────────────────────────────────────────

interface AddCookieModalProps {
  isOpen: boolean
  onClose: () => void
  onSave: (data: AddCookieFormData) => void
  onTest: (data: AddCookieFormData) => void
}

export function AddCookieModal({ isOpen, onClose, onSave, onTest }: AddCookieModalProps) {
  const [form, setForm] = useState<AddCookieFormData>(DEFAULT_ADD_FORM)
  const [testing, setTesting] = useState(false)
  const [testResult, setTestResult] = useState<TestCookieResponse | null>(null)

  // Reset form on open
  useEffect(() => {
    if (isOpen) { setForm(DEFAULT_ADD_FORM); setTestResult(null) }
  }, [isOpen])

  // Escape to close
  useEffect(() => {
    if (!isOpen) return
    function onEsc(e: KeyboardEvent) {
      if (e.key === 'Escape') onClose()
    }
    document.addEventListener('keydown', onEsc)
    return () => document.removeEventListener('keydown', onEsc)
  }, [isOpen, onClose])

  if (!isOpen) return null

  function set<K extends keyof AddCookieFormData>(key: K, value: AddCookieFormData[K]) {
    setForm(prev => ({ ...prev, [key]: value }))
  }

  async function handleTest() {
    if (!form.platform || !form.rawCookie) return
    setTesting(true)
    setTestResult(null)
    try {
      const result = await testCookieApi(form.platform, form.rawCookie)
      setTestResult(result)
      onTest(form)
    } catch (e) {
      setTestResult({ ok: false, message: (e as Error).message ?? 'Test failed' })
    } finally {
      setTesting(false)
    }
  }

  const canSubmit = form.platform && form.accountLabel && form.rawCookie
  const hint = FORMAT_HINTS[form.importMode]

  return (
    <>
      {/* Backdrop */}
      <div
        className="fixed inset-0 z-40 bg-surface-2 backdrop-blur-sm"
        onClick={onClose}
        aria-hidden
      />

      {/* Dialog */}
      <div className="fixed inset-0 z-50 flex items-center justify-center overflow-y-auto p-4">
        <div
          className="relative w-full max-w-lg rounded-2xl border border-line bg-canvas shadow-2xl"
          onClick={e => e.stopPropagation()}
          role="dialog"
          aria-modal
          aria-label="Add cookie"
        >
          {/* ── Header ── */}
          <div className="flex items-center justify-between border-b border-line px-5 py-4">
            <div>
              <h2 className="text-sm font-semibold text-fg">Add Cookie</h2>
              <p className="mt-0.5 text-xs text-fg-muted">
                Import a session cookie into the pool for the selected platform.
              </p>
            </div>
            <button
              onClick={onClose}
              className="flex h-7 w-7 items-center justify-center rounded text-fg-muted hover:bg-surface hover:text-fg-2"
              aria-label="Close"
            >
              <svg viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth={2} className="h-4 w-4">
                <path strokeLinecap="round" d="M6 18L18 6M6 6l12 12" />
              </svg>
            </button>
          </div>

          {/* ── Form ── */}
          <div className="flex flex-col gap-4 px-5 py-4">
            {/* Row: Platform + Account Label */}
            <div className="grid grid-cols-2 gap-3">
              <div>
                <Label required>Platform</Label>
                <SelectBase
                  value={form.platform}
                  onChange={e => set('platform', e.target.value)}
                >
                  <option value="">Select platform…</option>
                  {PLATFORMS.map(p => (
                    <option key={p} value={p}>
                      {p.charAt(0).toUpperCase() + p.slice(1)}
                    </option>
                  ))}
                </SelectBase>
              </div>

              <div>
                <Label required>Account Label</Label>
                <InputBase
                  value={form.accountLabel}
                  onChange={e => set('accountLabel', e.target.value)}
                  placeholder="e.g. yt_main_2024"
                />
              </div>
            </div>

            {/* Import Mode selector */}
            <div>
              <Label>Import Format</Label>
              <div className="flex gap-2">
                {IMPORT_MODES.map(m => (
                  <button
                    key={m.value}
                    type="button"
                    onClick={() => set('importMode', m.value)}
                    className={cn(
                      'flex-1 rounded-lg border py-1.5 text-center text-xs font-medium transition-colors',
                      form.importMode === m.value
                        ? 'border-line bg-surface-2 text-fg-2'
                        : 'border-line text-fg-muted hover:border-line-strong hover:text-fg-2',
                    )}
                  >
                    {m.label}
                  </button>
                ))}
              </div>
              <p className="mt-1.5 text-[11px] text-fg-muted">{hint.hint}</p>
            </div>

            {/* Cookie textarea */}
            <div>
              <Label required>Cookie Data</Label>
              <textarea
                value={form.rawCookie}
                onChange={e => set('rawCookie', e.target.value)}
                placeholder={hint.placeholder}
                rows={6}
                className={cn(
                  'w-full resize-y rounded-lg border border-line bg-surface px-3 py-2.5',
                  'font-mono text-[11px] text-fg-2 placeholder:text-fg-muted',
                  'outline-none transition-colors focus:border-line focus:ring-1 focus:ring-line-strong',
                )}
                spellCheck={false}
              />
            </div>

            {/* Notes (optional) */}
            <div>
              <Label>Notes (optional)</Label>
              <InputBase
                value={form.notes}
                onChange={e => set('notes', e.target.value)}
                placeholder="e.g. Sourced from prod env 2024-12, rotate when fails"
              />
            </div>

            {/* Format info box */}
            <div className="rounded-card border border-line bg-surface shadow-card p-3">
              <p className="mb-1.5 text-[10px] font-semibold uppercase tracking-widest text-fg-muted">
                Accepted formats
              </p>
              <div className="flex flex-col gap-1">
                {IMPORT_MODES.map(m => (
                  <div
                    key={m.value}
                    className={cn(
                      'flex items-start gap-2 rounded-md px-2 py-1.5 text-[11px] transition-colors',
                      form.importMode === m.value
                        ? 'bg-surface-2 text-fg-2'
                        : 'text-fg-muted',
                    )}
                  >
                    <span className="mt-0.5 font-mono font-semibold uppercase">{m.label}</span>
                    <span>{FORMAT_HINTS[m.value].hint}</span>
                  </div>
                ))}
              </div>
            </div>
          </div>

          {/* ── Test result ── */}
          {testResult && (
            <div className={cn(
              'mx-5 mb-1 rounded-lg border px-3 py-2.5 text-xs space-y-1',
              testResult.ok
                ? 'border-success/60 bg-success-soft text-success'
                : 'border-danger/60 bg-danger-soft text-danger',
            )}>
              <div className="flex items-center gap-2 font-semibold">
                {testResult.ok
                  ? <span className="text-success">✓ Cookie valid</span>
                  : <span className="text-danger">✗ Cookie invalid</span>
                }
              </div>
              <p className="text-[11px] opacity-90">{testResult.message}</p>
              {testResult.missing_keys && testResult.missing_keys.length > 0 && (
                <p className="text-[11px] opacity-70">Missing: {testResult.missing_keys.join(', ')}</p>
              )}
            </div>
          )}

          {/* ── Footer ── */}
          <div className="flex items-center justify-between border-t border-line px-5 py-3">
            <button
              onClick={onClose}
              className="rounded-lg border border-line px-4 py-1.5 text-xs font-medium text-fg-muted transition-colors hover:border-line-strong hover:text-fg-2"
            >
              Cancel
            </button>

            <div className="flex gap-2">
              <button
                onClick={handleTest}
                disabled={!form.platform || !form.rawCookie || testing}
                className={cn(
                  'flex items-center gap-1.5 rounded-lg border px-4 py-1.5 text-xs font-medium transition-colors',
                  'border-line text-fg-2 hover:border-line-strong hover:bg-surface',
                  'disabled:cursor-not-allowed disabled:opacity-40',
                )}
              >
                {testing ? (
                  <svg className="h-3 w-3 animate-spin" viewBox="0 0 24 24" fill="none">
                    <circle className="opacity-25" cx="12" cy="12" r="10" stroke="currentColor" strokeWidth="4" />
                    <path className="opacity-75" fill="currentColor" d="M4 12a8 8 0 018-8v8H4z" />
                  </svg>
                ) : (
                  <svg viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth={1.75} className="h-3 w-3">
                    <path strokeLinecap="round" strokeLinejoin="round" d="M13 10V3L4 14h7v7l9-11h-7z" />
                  </svg>
                )}
                {testing ? 'Testing…' : 'Test Cookie'}
              </button>

              <button
                onClick={() => onSave(form)}
                disabled={!canSubmit}
                className={cn(
                  'rounded-lg bg-accent px-4 py-1.5 text-xs font-semibold text-accent-fg transition-colors hover:bg-accent-hover',
                  'disabled:cursor-not-allowed disabled:opacity-40',
                )}
              >
                Save Cookie
              </button>
            </div>
          </div>
        </div>
      </div>
    </>
  )
}
