import type { CookieItem, CookiePoolSummary } from './cookie.types'

export const MOCK_COOKIES: CookieItem[] = [
  // ── YouTube pool (3 cookies) ───────────────────────────────────────────────
  {
    id: 'yt-1',
    platform: 'youtube',
    accountLabel: 'yt_main_2024',
    status: 'active',
    healthScore: 92,
    lastSuccessAt: '2m ago',
    lastFailAt: null,
    failCount: 0,
    cooldownRemainingSec: 0,
    expiryEstimate: '~8 months',
  },
  {
    id: 'yt-2',
    platform: 'youtube',
    accountLabel: 'yt_backup_01',
    status: 'hard_blocked',
    healthScore: 12,
    lastSuccessAt: '4h ago',
    lastFailAt: '3h ago',
    failCount: 7,
    cooldownRemainingSec: 14800,
    expiryEstimate: '~6 months',
  },
  {
    id: 'yt-3',
    platform: 'youtube',
    accountLabel: 'yt_reserve_02',
    status: 'active',
    healthScore: 78,
    lastSuccessAt: '15m ago',
    lastFailAt: '2h ago',
    failCount: 2,
    cooldownRemainingSec: 0,
    expiryEstimate: '~5 months',
  },

  // ── Instagram pool (5 cookies) ─────────────────────────────────────────────
  {
    id: 'ig-1',
    platform: 'instagram',
    accountLabel: 'ig_biz_account',
    status: 'soft_blocked',
    healthScore: 45,
    lastSuccessAt: '25m ago',
    lastFailAt: '18m ago',
    failCount: 3,
    cooldownRemainingSec: 540,
    expiryEstimate: '~3 months',
  },
  {
    id: 'ig-2',
    platform: 'instagram',
    accountLabel: 'ig_personal_01',
    status: 'active',
    healthScore: 88,
    lastSuccessAt: '4m ago',
    lastFailAt: null,
    failCount: 0,
    cooldownRemainingSec: 0,
    expiryEstimate: '~7 months',
  },
  {
    id: 'ig-3',
    platform: 'instagram',
    accountLabel: 'ig_creator_02',
    status: 'soft_blocked',
    healthScore: 35,
    lastSuccessAt: '32m ago',
    lastFailAt: '22m ago',
    failCount: 4,
    cooldownRemainingSec: 340,
    expiryEstimate: '~4 months',
  },
  {
    id: 'ig-4',
    platform: 'instagram',
    accountLabel: 'ig_business_03',
    status: 'hard_blocked',
    healthScore: 5,
    lastSuccessAt: '3h ago',
    lastFailAt: '2h ago',
    failCount: 9,
    cooldownRemainingSec: 18200,
    expiryEstimate: '~2 months',
  },
  {
    id: 'ig-5',
    platform: 'instagram',
    accountLabel: 'ig_reserve_04',
    status: 'active',
    healthScore: 95,
    lastSuccessAt: '8m ago',
    lastFailAt: null,
    failCount: 0,
    cooldownRemainingSec: 0,
    expiryEstimate: '~9 months',
  },

  // ── TikTok pool (2 cookies) ────────────────────────────────────────────────
  {
    id: 'tt-1',
    platform: 'tiktok',
    accountLabel: 'tt_primary',
    status: 'active',
    healthScore: 91,
    lastSuccessAt: '1m ago',
    lastFailAt: null,
    failCount: 0,
    cooldownRemainingSec: 0,
    expiryEstimate: '~11 months',
  },
  {
    id: 'tt-2',
    platform: 'tiktok',
    accountLabel: 'tt_secondary',
    status: 'active',
    healthScore: 84,
    lastSuccessAt: '6m ago',
    lastFailAt: '1h ago',
    failCount: 1,
    cooldownRemainingSec: 0,
    expiryEstimate: '~10 months',
  },

  // ── Facebook pool (2 cookies) ──────────────────────────────────────────────
  {
    id: 'fb-1',
    platform: 'facebook',
    accountLabel: 'fb_main',
    status: 'active',
    healthScore: 87,
    lastSuccessAt: '3m ago',
    lastFailAt: null,
    failCount: 0,
    cooldownRemainingSec: 0,
    expiryEstimate: '~6 months',
  },
  {
    id: 'fb-2',
    platform: 'facebook',
    accountLabel: 'fb_backup',
    status: 'expired',
    healthScore: 0,
    lastSuccessAt: '12d ago',
    lastFailAt: '10d ago',
    failCount: 15,
    cooldownRemainingSec: 0,
    expiryEstimate: 'Expired',
  },

  // ── Twitter / Untested ─────────────────────────────────────────────────────
  {
    id: 'tw-new',
    platform: 'twitter',
    accountLabel: 'tw_new_account',
    status: 'untested',
    healthScore: 50,
    lastSuccessAt: 'never',
    lastFailAt: null,
    failCount: 0,
    cooldownRemainingSec: 0,
    expiryEstimate: 'Unknown',
  },
  {
    id: 'ig-dis',
    platform: 'instagram',
    accountLabel: 'ig_old_burner',
    status: 'disabled',
    healthScore: 0,
    lastSuccessAt: '5d ago',
    lastFailAt: '4d ago',
    failCount: 11,
    cooldownRemainingSec: 0,
    expiryEstimate: '~1 month',
  },
]

export function computeSummary(cookies: CookieItem[]): CookiePoolSummary {
  return {
    total:        cookies.length,
    active:       cookies.filter(c => c.status === 'active').length,
    cooldown:     cookies.filter(c => c.status === 'soft_blocked' || c.status === 'hard_blocked').length,
    disabled:     cookies.filter(c => c.status === 'disabled' || c.status === 'expired').length,
    expiringSoon: cookies.filter(c => c.expiryEstimate.startsWith('~1') || c.expiryEstimate.startsWith('~2')).length,
  }
}
