#!/usr/bin/env python3
"""Regenerate the disposable-email blocklist (task #6039).

Writes two files from ONE pinned copy of the open list
https://github.com/disposable-email-domains/disposable-email-domains (CC0):

  database/migrations/036_block_disposable_email_signup.sql   (server gate)
  frontend/public/disposable-domains.json                     (early hint in the sign-up form)

The server trigger is the real gate; the JSON only lets the form say why
before the request is sent.

Usage (from the repo root):
  python3 scripts/gen-disposable-domains.py              # pinned commit below
  python3 scripts/gen-disposable-domains.py --file x.conf --commit <sha> --sha256 <hash>

To move to a newer list: pick a commit on the upstream main branch, download
disposable_email_blocklist.conf at that commit, put the commit + sha256 below
(or pass them), rerun, and ship a NEW migration (037_...) that only inserts —
036 must stay as it was run. Rows are inserted with ON CONFLICT DO NOTHING,
so re-running either migration is harmless.
"""
from __future__ import annotations

import argparse
import hashlib
import json
import re
import sys
import urllib.request
from pathlib import Path

REPO = "disposable-email-domains/disposable-email-domains"
COMMIT = "1aac72a07cd89792016dd5d2056bc418d85b8f14"  # main @ 2026-10-05T09:34:40Z
SHA256 = "a1390dd93de132a45d6ffd598375310531da5358805659df4113f0584f663ef4"
FILE = "disposable_email_blocklist.conf"

ROOT = Path(__file__).resolve().parent.parent
MIGRATION = ROOT / "database/migrations/036_block_disposable_email_signup.sql"
JSON_OUT = ROOT / "frontend/public/disposable-domains.json"

DOMAIN_RE = re.compile(r"^[a-z0-9-]+(\.[a-z0-9-]+)+$")


def load(args) -> bytes:
    if args.file:
        return Path(args.file).read_bytes()
    url = f"https://raw.githubusercontent.com/{REPO}/{args.commit}/{FILE}"
    with urllib.request.urlopen(url, timeout=60) as r:  # noqa: S310 (fixed https URL)
        return r.read()


def parse(raw: bytes) -> list[str]:
    out = set()
    for line in raw.decode("utf-8").splitlines():
        d = line.strip().lower()
        if not d or d.startswith("#"):
            continue
        if not DOMAIN_RE.match(d) or len(d) > 253:
            raise SystemExit(f"unexpected entry in upstream list: {d!r}")
        out.add(d)
    return sorted(out)


HEADER = """\
-- 036 — Reject sign-ups that use a disposable / temporary email domain
--       (AI Factory task #6039, anti-spam for sign-up).
--
-- GENERATED by scripts/gen-disposable-domains.py — do not edit the seed by hand.
--
-- What it does
--   * public.blocked_email_domains   one row per blocked domain. Seeded from
--     https://github.com/{repo}
--     file {file} at commit {commit}
--     (sha256 {sha256}, {n} domains, licence CC0 1.0). All entries are included.
--   * public.signup_email_allowlist  exact email addresses that may sign up even
--     though their domain is blocked (escape hatch for the owner, see below).
--   * BEFORE INSERT trigger on auth.users: if the new user's email domain, or any
--     parent domain of it (x.mailinator.com -> mailinator.com), is in the table,
--     the insert fails with
--         VIDGRAB_DISPOSABLE_EMAIL: sign-up with a disposable email domain (<domain>) is not allowed
--     Supabase Auth then answers the sign-up request with HTTP 500
--     "Database error saving new user" (supabase-js sends API version 2024-01-01,
--     which does not forward the Postgres message); the web app maps that to a
--     Vietnamese message.
--
-- What it does NOT do
--   * Existing users are untouched: only INSERT is checked, never UPDATE, so
--     sign-in, token refresh, profile edits and email confirmation of accounts
--     that already exist keep working even if their domain is on the list.
--   * Users without an email (phone / anonymous) pass.
--   * Email CHANGE to a disposable address is not blocked (UPDATE is not
--     checked; the new address must still be confirmed by Supabase).
--
-- The service role / admin API
--   Supabase's admin API (service_role: auth.admin.createUser, inviteUserByEmail)
--   inserts through the same Auth server and database role as a normal sign-up,
--   so the database cannot tell them apart and the block applies there too.
--   To let one specific address in anyway, the owner runs (SQL editor):
--       INSERT INTO public.signup_email_allowlist (email, note)
--       VALUES (lower('someone@tempdomain.example'), 'why');
--   To unblock a whole domain:
--       DELETE FROM public.blocked_email_domains WHERE domain = 'example.com';
--   To block an extra domain:
--       INSERT INTO public.blocked_email_domains (domain, source)
--       VALUES ('spam.example', 'manual') ON CONFLICT DO NOTHING;
--
-- Rollback (removes the gate, keeps the data):
--     DROP TRIGGER IF EXISTS on_auth_user_block_disposable ON auth.users;
--   Full removal:
--     DROP TRIGGER IF EXISTS on_auth_user_block_disposable ON auth.users;
--     DROP FUNCTION IF EXISTS public.reject_disposable_email_signup();
--     DROP FUNCTION IF EXISTS public.email_domain_suffixes(text);
--     DROP TABLE IF EXISTS public.signup_email_allowlist;
--     DROP TABLE IF EXISTS public.blocked_email_domains;
--
-- Safe to run more than once. Run it in the Supabase SQL editor as postgres.
--
-- VERIFY (after):
--   SELECT count(*) FROM public.blocked_email_domains;          -- >= {n}
--   SELECT tgname, tgenabled FROM pg_trigger
--    WHERE tgrelid = 'auth.users'::regclass AND NOT tgisinternal; -- has on_auth_user_block_disposable

BEGIN;

CREATE TABLE IF NOT EXISTS public.blocked_email_domains (
    domain     text PRIMARY KEY
               CHECK (domain = lower(domain) AND domain ~ '^[a-z0-9-]+(\\.[a-z0-9-]+)+$'),
    source     text NOT NULL DEFAULT 'manual',
    created_at timestamptz NOT NULL DEFAULT now()
);

CREATE TABLE IF NOT EXISTS public.signup_email_allowlist (
    email      text PRIMARY KEY CHECK (email = lower(email) AND position('@' in email) > 1),
    note       text,
    created_at timestamptz NOT NULL DEFAULT now()
);

-- Not readable or writable through the public REST API: RLS on with no
-- policies, and no table grants for the client roles.
ALTER TABLE public.blocked_email_domains  ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.signup_email_allowlist ENABLE ROW LEVEL SECURITY;
DO $$
BEGIN
    IF EXISTS (SELECT 1 FROM pg_roles WHERE rolname = 'anon') THEN
        REVOKE ALL ON public.blocked_email_domains, public.signup_email_allowlist FROM anon;
    END IF;
    IF EXISTS (SELECT 1 FROM pg_roles WHERE rolname = 'authenticated') THEN
        REVOKE ALL ON public.blocked_email_domains, public.signup_email_allowlist FROM authenticated;
    END IF;
END $$;

-- 'a.b.example.com' -> {{a.b.example.com, b.example.com, example.com, com}}
CREATE OR REPLACE FUNCTION public.email_domain_suffixes(p_domain text)
RETURNS text[]
LANGUAGE sql
IMMUTABLE
SET search_path = ''
AS $$
    SELECT coalesce(array_agg(array_to_string(s.parts[i:], '.') ORDER BY i), '{{}}'::text[])
    FROM (SELECT string_to_array(p_domain, '.') AS parts) s,
         generate_series(1, coalesce(array_length(s.parts, 1), 0)) AS i
$$;

CREATE OR REPLACE FUNCTION public.reject_disposable_email_signup()
RETURNS trigger
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = ''
AS $$
DECLARE
    v_email  text := lower(btrim(coalesce(NEW.email, '')));
    v_domain text;
    v_hit    text;
BEGIN
    IF v_email = '' OR position('@' in v_email) = 0 THEN
        RETURN NEW;                       -- phone / anonymous users
    END IF;
    IF EXISTS (SELECT 1 FROM public.signup_email_allowlist a WHERE a.email = v_email) THEN
        RETURN NEW;
    END IF;
    v_domain := rtrim(substring(v_email from '@([^@]+)$'), '.');
    IF v_domain IS NULL OR v_domain = '' THEN
        RETURN NEW;
    END IF;
    SELECT b.domain INTO v_hit
      FROM public.blocked_email_domains b
     WHERE b.domain = ANY (public.email_domain_suffixes(v_domain))
     LIMIT 1;
    IF v_hit IS NOT NULL THEN
        RAISE EXCEPTION 'VIDGRAB_DISPOSABLE_EMAIL: sign-up with a disposable email domain (%) is not allowed', v_hit
            USING ERRCODE = 'P0001',
                  HINT = 'Use a permanent email address. Owner override: public.signup_email_allowlist.';
    END IF;
    RETURN NEW;
END;
$$;

REVOKE ALL ON FUNCTION public.email_domain_suffixes(text) FROM PUBLIC;
REVOKE ALL ON FUNCTION public.reject_disposable_email_signup() FROM PUBLIC;
DO $$
BEGIN
    IF EXISTS (SELECT 1 FROM pg_roles WHERE rolname = 'anon') THEN
        REVOKE ALL ON FUNCTION public.email_domain_suffixes(text) FROM anon;
        REVOKE ALL ON FUNCTION public.reject_disposable_email_signup() FROM anon;
    END IF;
    IF EXISTS (SELECT 1 FROM pg_roles WHERE rolname = 'authenticated') THEN
        REVOKE ALL ON FUNCTION public.email_domain_suffixes(text) FROM authenticated;
        REVOKE ALL ON FUNCTION public.reject_disposable_email_signup() FROM authenticated;
    END IF;
END $$;

DROP TRIGGER IF EXISTS on_auth_user_block_disposable ON auth.users;
CREATE TRIGGER on_auth_user_block_disposable
    BEFORE INSERT ON auth.users
    FOR EACH ROW EXECUTE FUNCTION public.reject_disposable_email_signup();

-- Seed: {n} domains from {repo} @ {commit}.
INSERT INTO public.blocked_email_domains (domain, source)
SELECT d, 'disposable-email-domains@{short}'
FROM unnest(ARRAY[
"""

FOOTER = """\
]) AS t(d)
ON CONFLICT (domain) DO NOTHING;

COMMIT;
"""


def main() -> None:
    ap = argparse.ArgumentParser()
    ap.add_argument("--file", help="local copy of disposable_email_blocklist.conf")
    ap.add_argument("--commit", default=COMMIT)
    ap.add_argument("--sha256", default=SHA256)
    args = ap.parse_args()

    raw = load(args)
    got = hashlib.sha256(raw).hexdigest()
    if got != args.sha256:
        raise SystemExit(f"sha256 mismatch: expected {args.sha256}, got {got}")
    domains = parse(raw)
    n = len(domains)

    head = HEADER.format(repo=REPO, file=FILE, commit=args.commit, sha256=args.sha256, n=n, short=args.commit[:7])
    body = ",\n".join(f"'{d}'" for d in domains)  # DOMAIN_RE guarantees no quotes
    MIGRATION.write_text(head + body + "\n" + FOOTER, encoding="utf-8", newline="\n")

    JSON_OUT.write_text(
        json.dumps({"source": f"https://github.com/{REPO}/blob/{args.commit}/{FILE}", "count": n, "domains": domains},
                   separators=(",", ":")) + "\n",
        encoding="utf-8", newline="\n",
    )
    print(f"{n} domains -> {MIGRATION.relative_to(ROOT)}, {JSON_OUT.relative_to(ROOT)}", file=sys.stderr)


if __name__ == "__main__":
    main()
